return {
	purple_lightning = {
	accuracy = 0,
	areaofeffect = 36,
	beamTTL = 10,
	beamtime = 0.1,
	-- largeBeamLaser = true,
	-- tileLength = 100, 
	-- scrollSpeed = 2,
	beamdecay = 0.5,
	craterareaofeffect = 0,
	craterboost = 0,
	cratermult = 0,
	duration = 1,
	energypershot = 25000,
	explosiongenerator = "custom:tll_spray_exp",
	firestarter = 90,
	impulseboost = 0,
	impulsefactor = 0,
	impactonly = true,
	name = "Purple Lightning",
	range = 2600,
	reloadtime = 1,
	rgbcolor = "0.8 0 0.9",
	-- soundstart = "hppc2",
	texture1 = "strike",
	thickness = 18,
	weapontype = "LightningCannon",
	customparams = {
		light_mult = 1.4,
		light_radius_mult = 0.9,
	},
	damage = {
		commanders = 1000,
		default = 5000,
		subs = 5,
	},
	tracks = false,
	}
}