return {
	corboucher = {
		buildangle = 8192,
		buildcostenergy = 910943,
		buildcostmetal = 72375,
		builder = false,
		buildpic = "corboucher.dds",
		buildtime = 750000,
		canattack = true,
		canstop = 1,
		category = "ALL SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "220 130 220",
		collisionvolumetype = "CylY",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Large Cluster Cannon",
		explodeas = "MEDIUM_BUILDINGEX",
		firestandorders = 1,
		footprintx = 12,
		footprintz = 12,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 72,
		mass = 72375,
		maxdamage = 225130,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "The Butcher",
		noautofire = false,
		objectname = "core/corboucher.s3o",
		radardistance = 0,
		radaremitheight = 71,
		selfdestructas = "MEDIUM_BUILDING",
		sightdistance = 1500,
		standingfireorder = 2,
		unitname = "corboucher",
		yardmap = "oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo oooooooooooo",
		customparams = {
			buildpic = "corboucher.dds",
			faction = "CORE",
			normaltex = "unittextures/core_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 32000,
				description = "The Butcher Wreckage",
				featuredead = "heap",
				footprintx = 4,
				footprintz = 4,
				metal = 25687,
				object = "core/corboucher_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 40000,
				description = "The Butcher Debris",
				footprintx = 3,
				footprintz = 3,
				metal = 13700,
				object = "3x3d.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			cloak = "kloak1",
			uncloak = "kloak1un",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"twrturn3",
			},
			select = {
				"twrturn3",
			},
		},
		weapondefs = {
			core_boucher = {
				stockpile = true, 
				stockpileTime = 5,
				areaofeffect = 360,
				avoidfeature = false,
				burst = 2, 
				burstRate = 0.2,
				projectiles = 20,
				cegtag = "Trail_dmc_core",
				collidefriendly = false,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				duration = 0.025,
				energypershot = 120000,
				explosiongenerator = "custom:cordmc_explosion",
				firestarter = 90,
				impactonly = 1,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 0.75,
				name = "Cluster Cannon",
				nogap = 1,
				noselfdamage = true,
				range = 2000,
				reloadtime = 1,
				rgbcolor = "1 0.15 0.15",
				size = 2.5,
				sizedecay = -0.25,
				soundhitdry = "xplolrg1",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "lbx1",
				soundTrigger = true, 
				stages = 20,
				sprayangle = 1800,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 2400,
				damage = {
					commanders = 200,
					default = 5000, -- total ~100000 damage if all hits -> very good at large targets
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				badtargetcategory = "LARGE MEDIUM SMALL MINOR",
				def = "CORE_BOUCHER",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}