return {
	armanni1 = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 4096,
		buildcostenergy = 346000,
		buildcostmetal = 19270,
		builder = false,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 11,
		buildinggrounddecalsizey = 11,
		buildinggrounddecaltype = "armanni1_aoplane.dds",
		buildpic = "armanni1.dds",
		buildtime = 260000,
		canattack = true,
		canstop = 1,
		category = "ALL SURFACE",
		corpse = "dead",
		damagemodifier = 0.2,
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Super Tachyon Accelerator",
		energystorage = 2000,
		energyuse = 0,
		explodeas = "CRAWL_BLASTSML",
		firestandorders = 1,
		footprintx = 8,
		footprintz = 8,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 158,
		mass = 18270,
		maxdamage = 35000,
		maxslope = 10,
		maxvelocity = 0,
		maxwaterdepth = 0,
		name = "Advanced Annihilator",
		objectname = "arm/armanni1.s3o",
		onoffable = true,
		radardistance = 1500,
		radaremitheight = 158,
		seismicsignature = 0,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 780,
		standingfireorder = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		unitname = "armanni1",
		usebuildinggrounddecal = true,
		yardmap = "oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo",
		customparams = {
			buildpic = "armanni1.dds",
			faction = "ARM",
			normaltex = "unittextures/arm_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 17214,
				description = "Advanced Annihilator Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 7,
				footprintz = 7,
				metal = 10650,
				object = "arm/armanni1_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 21517,
				description = "Advanced Annihilator Debris",
				energy = 0,
				footprintx = 6,
				footprintz = 6,
				metal = 5680,
				object = "6x6b.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"anni",
			},
			select = {
				"anni",
			},
		},
		-- I want to make ARM and TALON beam weapons distinct in style, similar in damage
		-- ARM will draw from a stockpile and fire in style of BT pulse lasers 
		weapondefs = {
			ata10 = {
				areaofeffect = 56,
				avoidfeature = false,
				beamburst=true, -- this should work
				beamtime = 0.10,
				burst = 8, 
				burstTime = 0.0875, -- burst time total = 0.125s, 8 bursts = 1s
				beamdecay = 0.05,
				corethickness = 0.39,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				energypershot = 20000,
				explosiongenerator = "custom:LARGE_BURN_WHITE",
				impulseboost = 0,
				impulsefactor = 0,
				impactonly = false,
				laserflaresize = 20,
				name = "ATA",
				noselfdamage = true,
				range = 2150,
				reloadtime = 3, -- initial high alpha, falls back to close to old anni after stockpile use. 
				rgbcolor = "0.2 0.2 1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "pulselaser2",
				soundtrigger = true,
				sweepfire = true,
				stockpile = true, 
				stockpileTime = 10,
				targetmoveerror = 0.3,
				thickness = 10,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 1400,
				customparams = {
					light_mult = 1.2,
					light_radius_mult = 0.6,
				},
				damage = {
					commanders = 150,
					default = 2375,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				badtargetcategory = "MEDIUM SMALL MINOR",
				def = "ATA10",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}