return {
    ["purple_explosion_S"] = {
    generatorpop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 18,
        heatfalloff        = 0.8,
        maxheat            = 18,
        pos                = [[0, 0 0, 0]],
        size               = 60,
        sizegrowth         = -0.2,
        speed              = [[r0.35 r-0.35, 0 0, r0.35 r-0.35]],
        texture            = [[purpleexplo]],
      },
    },
    generatorpop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.7,
        maxheat            = 15,
        pos                = [[0, 0 0, 0]],
        size               = 50,
        sizegrowth         = -0.2,
        speed              = [[1 r0.35, 0 0, 1 r0.35]],
        texture            = [[pinkexplo]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0.4,
      circlegrowth       = 5,
      flashalpha         = 0.9,
      flashsize          = 110,
      ground             = true,
      ttl                = 20,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.10000000149012,
        [3]  = 0.89999997615814,
      },
    },
    smoke = {
      air                = true,
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.04,
        color              = 0.1,
        pos                = [[0, -1, 0]],
        size               = 30,
        sizeexpansion      = -0.6,
        sizegrowth         = 15,
        speed              = [[0, 1 r1.3, 0]],
        startsize          = 10,
      },
    },
    smoke00 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r-3, 0, 0 r-3]],
      },
    },
    smoke01 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r3, 0, 0 r3]],
      },
    },
    smoke02 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r3, 0, 0 r-3]],
      },
    },
    smoke04 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r-3, 0, 0 r3]],
      },
    },
  },

  ["purple_explosion_L"] = {
    generatorpop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 18,
        heatfalloff        = 0.8,
        maxheat            = 18,
        pos                = [[0, 0 0, 0]],
        size               = 240,
        sizegrowth         = -0.2,
        speed              = [[r0.35 r-0.35, 0 0, r0.35 r-0.35]],
        texture            = [[purpleexplo]],
      },
    },
    generatorpop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        heat               = 10,
        heatfalloff        = 0.7,
        maxheat            = 15,
        pos                = [[0, 0 0, 0]],
        size               = 230,
        sizegrowth         = -0.2,
        speed              = [[1 r0.35, 0 0, 1 r0.35]],
        texture            = [[pinkexplo]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0.4,
      circlegrowth       = 5,
      flashalpha         = 0.9,
      flashsize          = 110,
      ground             = true,
      ttl                = 20,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.10000000149012,
        [3]  = 0.89999997615814,
      },
    },
    smoke = {
      air                = true,
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.04,
        color              = 0.1,
        pos                = [[0, -1, 0]],
        size               = 30,
        sizeexpansion      = -0.6,
        sizegrowth         = 15,
        speed              = [[0, 1 r1.3, 0]],
        startsize          = 10,
      },
    },
    smoke00 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r-3, 0, 0 r-3]],
      },
    },
    smoke01 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r3, 0, 0 r3]],
      },
    },
    smoke02 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r3, 0, 0 r-3]],
      },
    },
    smoke04 = {
      air                = true,
      class              = [[smoke]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.08,
        color              = [[0.3 r0.3]],
        pos                = [[0, 0 r4, 0]],
        size               = [[15 r5]],
        sizegrowth         = 1,
        speed              = [[0 r-3, 0, 0 r3]],
      },
    },
  },
}