return {
	tlldmc = {
		buildangle = 8192,
		buildcostenergy = 742043,
		buildcostmetal = 71404,
		builder = false,
		buildpic = "tlldmc.dds",
		buildtime = 750000,
		canattack = true,
		canstop = 1,
		category = "ALL SURFACE",
		collisionvolumeoffsets = "0 -5 -3",
		collisionvolumescales = "145 120 155",
		collisionvolumetype = "Box",
		corpse = "dead",
		defaultmissiontype = "GUARD_NOMOVE",
		description = "Rift Cascade Emitter",
		explodeas = "MEDIUM_BUILDINGEX",
		firestandorders = 1,
		footprintx = 10,
		footprintz = 10,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 49,
		mass = 57404,
		maxdamage = 208025,
		maxslope = 10,
		maxwaterdepth = 0,
		name = "Tesseract",
		noautofire = false,
		objectname = "tll/tlldmc.s3o",
		radardistance = 0,
		radaremitheight = 75,
		selfdestructas = "MEDIUM_BUILDING",
		sightdistance = 1500,
		standingfireorder = 0,
		unitname = "tlldmc",
		yardmap = "oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo oooooooooo",
		customparams = {
			buildpic = "tlldmc.dds",
			canareaattack = 1,
			faction = "TLL",
			normaltex = "unittextures/tll_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = false,
				damage = 32000,
				description = "DMC Wreckage",
				energy = 0,
				featuredead = "heap",
				footprintx = 3,
				footprintz = 3,
				metal = 27892,
				object = "tll/tlldmc_dead.s3o",
				reclaimable = false,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 40000,
				description = "DMC Debris",
				energy = 0,
				footprintx = 3,
				footprintz = 3,
				metal = 14876,
				object = "3x3e.s3o",
				reclaimable = false,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			explosiongenerators = {
				"custom:tlldmc_flare",
			},
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"arm-bld-defense-action-t3",
			},
			select = {
				"arm-bld-defense-action-t3",
			},
		},
		weapondefs = {
			tlldmc = {
                areaofeffect = 360,
                beamtime = 3,
                corethickness = 1.2,
                largebeamlaser = true,
                laserflaresize = 20,
                thickness = 12,
                avoidfeature = false,
                cegtag = "Trail_dmc_tll",
                collidefriendly = false,
                craterareaofeffect = 380,
                craterboost = 0,
                cratermult = 0,
                energypershot = 224000, -- needs this for balance
                explosiongenerator = "custom:rift_cascade",
                firestarter = 90,
                impactonly = 1,
                impulseboost = 0,
                impulsefactor = 0,
                intensity = 0.75,
                name = "Rift Opener",
                nogap = 1,
                noselfdamage = true,
                range = 1700,
                reloadtime = 10,
                rgbcolor = "0.8 0.1 1.0",
                soundhitdry = "sizzle",
                soundhitwet = "splslrg",
                soundhitwetvolume = 0.6,
                soundstart = "heavylarge4",
                stages = 20,
                turret = true,
                weapontype = "BeamLaser",
                damage = {
                        commanders = 6400,
                        default = 64000,
                        subs = 5,
                },
                tracks = false,
            },
		},
		weapons = {
			{
				badtargetcategory = "MEDIUM SMALL MINOR LARGE",
				def = "tlldmc",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}