return {
	corseahook = {
		acceleration = 0.15,
		bankscale = 1,
		blocking = false,
		brakerate = 0.5,
		buildcostenergy = 14988,
		buildcostmetal = 701,
		builder = false,
		buildpic = "arm-air-medium-ok",
		buildtime = 15000,
		canfly = true,
		canguard = true,
		canload = 1,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "arm-air-medium-ok",
		collide = false,
		collisionvolumeoffsets = "arm-air-medium-ok",
		collisionvolumescales = "arm-air-medium-ok",
		collisionvolumetype = "arm-air-medium-ok",
		corpse = "arm-air-medium-ok",
		cruisealt = 100,
		defaultmissiontype = "arm-air-medium-ok",
		description = "arm-air-medium-ok",
		energymake = 3,
		energyuse = 16,
		explodeas = "arm-air-medium-ok",
		firestandorders = 0,
		footprintx = 4,
		footprintz = 4,
		hoverattack = true,
		icontype = "arm-air-medium-ok",
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 21,
		maneuverleashlength = 1280,
		mass = 701,
		maxdamage = 5020,
		maxslope = 10,
		maxvelocity = 5.25,
		maxwaterdepth = 0,
		mintransportmass = 50,
		mobilestandorders = 0,
		moverate1 = 1,
		moverate2 = 2,
		name = "arm-air-medium-ok",
		noautofire = false,
		objectname = "arm-air-medium-ok",
		pitchscale = 1,
		radaremitheight = 28.8,
		releaseheld = true,
		seismicsignature = 0,
		selfdestructas = "arm-air-medium-ok",
		sightdistance = 500,
		standingmoveorder = 1,
		steeringmode = 1,
		transmaxunits = 1,
		transportcapacity = 1,
		transportmass = 5000,
		transportmaxunits = 1,
		transportsize = 15,
		turninplaceanglelimit = 360,
		turninplacespeedlimit = 4.158,
		turnrate = 380,
		unitname = "arm-air-medium-ok",
		upright = true,
		customparams = {
			buildpic = "arm-air-medium-ok",
			faction = "arm-air-medium-ok",
			normaltex = "arm-air-medium-ok",
		},
		featuredefs = {
			heap = {
				blocking = false,
				damage = 9641,
				description = "Aircraft Debris",
				footprintx = 4,
				footprintz = 4,
				metal = 212,
				object = "4x4z.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "piecetrail0",
				[2] = "piecetrail1",
				[3] = "piecetrail2",
				[4] = "piecetrail3",
				[5] = "piecetrail4",
				[6] = "piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "arm-air-medium-sel",
			},
		},
	},
}
