return {
	tllblind = {
		acceleration = 0.06,
		airsightdistance = 920,
		brakerate = 0.45,
		buildcostenergy = 61430,
		buildcostmetal = 3245,
		builder = false,
		buildpic = "tllblind.dds",
		buildtime = 5500,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL LARGE MOBILE SURFACE UNDERWATER",
		collisionvolumeoffsets = "0 -5 0",
		collisionvolumescales = "61 64 39",
		collisionvolumetype = "ellipsoid",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Heavy Armored Mainline Kbot (Sniper Resistant)",
		explodeas = "CRAWL_BLAST",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 51,
		maneuverleashlength = 640,
		mass = 5754,
		maxdamage = 23715,
		maxslope = 14,
		maxvelocity = 1.2,
		maxwaterdepth = 21,
		mobilestandorders = 1,
		movementclass = "hkbot4",
		name = "Dreadnought",
		noautofire = false,
		objectname = "tll/tllblind.s3o",
		radardistance = 0,
		radaremitheight = 51,
		seismicsignature = 0,
		selfdestructas = "CRAWL_BLAST",
		sightdistance = 450,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0.726,
		turnrate = 650,
		unitname = "tllblind",
		upright = true,
		customparams = {
			buildpic = "tllblind.dds",
			faction = "TLL",
			normaltex = "unittextures/tll_normals.dds",
		},
		featuredefs = {
			dead = {
				blocking = true,
				damage = 16470,
				description = "Dreadnought Wreckage",
				featuredead = "heap",
				footprintx = 4,
				footprintz = 4,
				metal = 5737,
				object = "tll/tllblind_dead.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
			heap = {
				blocking = false,
				damage = 20588,
				description = "Dreadnought Debris",
				footprintx = 3,
				footprintz = 3,
				metal = 3060,
				object = "3x3c.s3o",
				reclaimable = true,
				customparams = {
					fromunit = 1,
				},
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				"piecetrail0",
				"piecetrail1",
				"piecetrail2",
				"piecetrail3",
				"piecetrail4",
				"piecetrail6",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				"cantdo4",
			},
			count = {
				"count6",
				"count5",
				"count4",
				"count3",
				"count2",
				"count1",
			},
			ok = {
				"kbcormov",
			},
			select = {
				"kbcorsel",
			},
		},
		weapondefs = {
			cor_gol = {
				areaofeffect = 725,
				avoidfeature = false,
				cegtag = "Trail_cannon",
				craterareaofeffect = 325,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH96",
				gravityaffected = true,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				name = "Heavy Cannon",
				nogap = 1,
				noselfdamage = true,
				range = 650,
				reloadtime = 4,
				rgbcolor = "1.0 0.5 0.0",
				separation = 0.45,
				sizedecay = -0.15,
				soundhitdry = "xplomed4",
				soundhitwet = "splslrg",
				soundhitwetvolume = 0.6,
				soundstart = "AC20",
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 310,
				damage = {
					default = 2400,
					subs = 5,
				},
				tracks = false,
			},
			rave_missile = {
				acceleration = 0.3,
				areaofeffect = 96,
				avoidfeature = false,
				cegtag = "Tll_titan_trail",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:Explosion_Medium_VLight",
				firestarter = 70,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "titan_missile.s3o",
				name = "Mini-Rocket",
				noselfdamage = true,
				proximitypriority = -1,
				range = 900,
				reloadtime = 1.5,
				smoketrail = true,
				soundhitdry = "xplosml2",
				soundhitwet = "splshbig",
				soundhitwetvolume = 0.6,
				soundstart = "clrm1",
				startvelocity = 220,
				targetable = 16,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 9000,
				tracks = false,
				turnrate = 35000,
				weaponacceleration = 150,
				weapontimer = 0.6,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2100,
				damage = {
					default = 150,
					subs = 5,
				},
			},
			tll_lightning = { -- flame
				areaofeffect = 186,
				burst = 40,
				burstrate = 0.01,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				firestarter = 300,
				impactonly = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Heavy Flamer",
				noselfdamage = true,
				range = 750,
				reloadtime = 2,
				rgbcolor = "0.9 0.9 0.2",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundhitwetvolume = 0.5,
				soundstart = "Flamer2",
				soundtrigger = 1,
				texture1 = "spray",
				sprayangle = 1800,
				tolerance = 2500,
				turret = true,
				weapontype = "Flame",
				weaponvelocity = 300,
				customparams = {
					light_mult = 1.4,
					light_radius_mult = 0.9,
				},
				damage = {
					default = 50,
					subs = 5,
				},
				tracks = false,
			},
		},
		weapons = {
			{
				def = "COR_GOL",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "RAVE_MISSILE",
				onlytargetcategory = "SURFACE",
			},
			{
				def = "TLL_LIGHTNING",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}